import math 

NUM_MEMORY_BLOCKS_IN_SOUP = 1000#2000
CHECKED_ADDRESS_STACK_SIZE = 20 # for the monitor command

REGISTER_WRITE_MUTATION_PROBABILITY = 0#0.01
REGISTER_WRITE_MUTATION_RANGE       = (0,0)#(-3, 3)

RANDOMIZE_BLOCK_ON_WRITE_CHANCE = 0#0.001

